#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = ["pyyaml>=6"]
# ///
"""provision.py — the channel provisioner.

Reconciles an Initiative's Buzz channels to taxonomy.yml (derived from canon/buildops-canon.md).
Honors lazy instantiation (B6): the default set is just the home + product channels; other tracks are
added on demand with --track. Enrolls the taxonomy's members, and writes the Notifier's per-initiative
facet routing. Idempotent — it creates only missing channels and is safe to re-run.

  uv run provision.py --initiative arxus                 # default lazy set: home + product
  uv run provision.py --initiative arxus --track gtm      # add an on-demand track channel
  uv run provision.py --initiative acme --visibility private
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT / "control-plane"))
from buzz import BuzzClient, canonical_channel_name

TAX = ROOT / "taxonomy.yml"
NOTIFY = ROOT / "notify.yml"


def _load(p: Path) -> dict:
    return yaml.safe_load(p.read_text()) if p.exists() else {}


def _channel_name(initiative: str, suffix: str) -> str:
    return initiative if not suffix else f"{initiative}-{suffix}"


def _save_notify(notify: dict) -> None:
    header = ("# Notifier port config — routing generated by provision.py from taxonomy.yml.\n"
              "# channels.<initiative> is a facet->UUID map (the (initiative, track) routing, B11);\n"
              "# channels.default is the global escalations fallback. adapter/events are hand-set.\n")
    NOTIFY.write_text(header + yaml.safe_dump(notify, sort_keys=False))


def provision(initiative: str, add_tracks: list[str] | None, visibility: str | None) -> dict:
    tax = _load(TAX)
    client = BuzzClient.from_env()
    existing = {ch["name"]: ch["channel_id"] for ch in client.list_channels()}
    vis = visibility or tax["initiative_defaults"]["visibility"]
    members = tax.get("members", []) or []

    targets: list[tuple[str, str]] = []          # (facet-key, channel-name)
    for spec in tax["initiative_defaults"]["channels"]:
        targets.append((spec["key"], _channel_name(initiative, spec["suffix"])))
    for t in (add_tracks or []):
        if t not in tax.get("tracks", {}):
            print(f"  ! unknown track '{t}' — known: {', '.join(tax.get('tracks', {}))}")
            continue
        targets.append((t, _channel_name(initiative, tax["tracks"][t]["suffix"])))

    routes: dict[str, str] = {}
    for key, name in targets:
        cname = canonical_channel_name(name)
        if cname in existing:
            cid, status = existing[cname], "exists"
        else:
            cid, resp = client.create_channel(name, visibility=vis, about=f"{initiative} — {key} track")
            if not (isinstance(resp, dict) and resp.get("accepted")):
                print(f"  ✗ create {name} rejected -> {resp}")
                continue
            existing[cname] = cid
            status = "created"
        for m in members:                        # idempotent; the relay dedupes membership
            client.add_member(cid, m, role="admin")
        routes[key] = cid
        mark = "＋" if status == "created" else "✓"
        print(f"  {mark} {name:26s} {status:8s} {cid}  (+{len(members)} member)")

    notify = _load(NOTIFY)
    notify.setdefault("adapter", "buzz")
    notify.setdefault("channels", {})
    cur = notify["channels"].get(initiative)
    if isinstance(cur, dict):
        cur.update(routes)                       # merge: keep facets from earlier runs
    else:
        notify["channels"][initiative] = routes
    notify.setdefault("events", {"escalated": True, "accepted": True})
    _save_notify(notify)
    print(f"  → notify.yml: channels.{initiative} = {routes}")
    return routes


def main(argv):
    ap = argparse.ArgumentParser()
    ap.add_argument("--initiative", required=True)
    ap.add_argument("--track", action="append", help="add an on-demand track channel (repeatable)")
    ap.add_argument("--visibility", choices=["open", "private"])
    a = ap.parse_args(argv)
    extra = f" + tracks {a.track}" if a.track else ""
    print(f"provisioning initiative '{a.initiative}' (lazy default set{extra}):")
    provision(a.initiative, a.track, a.visibility)


if __name__ == "__main__":
    main(sys.argv[1:])
